apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop-dev
  region: eu-central-1

managedNodeGroups:
  - name: managed-ng-public
    instanceTypes: ["t3.small", "t3.medium"]
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    spot: true
